spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?createDatabaseIfNotExist=true # &allowPublicKeyRetrieval=true
    username: root
    password: 123

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: always
      continue-on-error: false

  springdoc:
    swagger-ui:
      path: /swagger-ui.html

jwt:
  secret: supersecretcomplexsecret

logging:
  level:
    org:
      springframework:
        security: DEBUG
